services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: contented
      POSTGRES_PASSWORD: example
    volumes:
      - .volumes/postgres:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@contented.local
      PGADMIN_DEFAULT_PASSWORD: example
    depends_on:
      - postgres
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      cluster.name: elastic-cluster
      xpack.security.enabled: "false"
    volumes:
      - .volumes/elasticsearch:/usr/share/elasticsearch/data
